services:
  ampcast:
    image: ghcr.io/rekkyrosso/ampcast:0.9.24
    container_name: ampcast
    networks:
      docker_network:
        ipv4_address: ${AMPCAST_IP}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "${AMPCAST_EXT_PORT}:${AMPCAST_INT_PORT}"
    environment:
      ENABLED_SERVICES: "navidrome"
      STARTUP_SERVICES: "navidrome"
      NAVIDROME_HOST: "http://{IP_SERVER}:${NAVIDROME_PORT}"
