services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v9.0.2
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      socket_proxy:
        ipv4_address: ${DOZZLE_PROXY_IP}
      docker_network:
        ipv4_address: ${DOZZLE_IP}
    ports:
      - "${DOZZLE_EXT_PORT}:${DOZZLE_INT_PORT}"
    environment:
      DOZZLE_LEVEL: "info"
      DOCKER_HOST: "tcp://socket-proxy:${SOCKET_PROXY_PORT}"
